### ISSUE TITLE
Can't get WSDL 

### ISSUE THREAD

**Issue by ACCLT1** [StefH/WSDLGenerator#3]
When try to generate wsdl Get error: Invalid namespace, 'http://xxxx.com/validation/ticketing' does not end with a /

Is it possible to ignore it or add / by the ttol?

**Comment by StefH** [comment]
@ACCLT1 
Can you please provide the full commandline and if possible also the dll's ?

**Comment by ACCLT1** [comment]
[58-TicketingImplementation.zip](https://github.com/StefH/WSDLGenerator/files/14075765/58-TicketingImplementation.zip)

WSDLGenerator.exe -i 58-TicketingImplementation.dll -o c:\temp -w

Invalid namespace, 'http://observeit.com/validation/ticketing' does not end with a /
Invalid namespace, 'http://observeit.com/validation/ticketing' does not end with a /

**Comment by StefH** [comment]
https://github.com/StefH/WSDLGenerator/pull/4

**Comment by StefH** [comment]
@ACCLT1 
Release `0.0.0.14` is uploaded.

**Comment by ACCLT1** [comment]
Great respond and fix. Thanks!
